name: Cat Image Validation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  validate-cat-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: pip install requests opencv-python numpy

    - name: GET Cat Image
      run: src/get_cat_image.py
      env:
        CATS_API_KEY: ${{ secrets.CATS_API_KEY }}

    - name: Check Cat Image
      run: src/checkcat_image.py
      env:
        CATS_API_KEY: ${{ secrets.CATS_API_KEY }}
