name: Cat Service

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  cat_service_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Get API key
        run: echo "CATS_API_KEY=${{ secrets.CATS_API_KEY }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: pip install requests opencv-python-headless

      - name: Get Cat Image
        run: python src/get_cat_image.py

      - name: Check Cat Image
        run: python src/check_cat_image.py 
