name: Always Fail Action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  fail:
    runs-on: ubuntu-latest
    steps:
      - name: Always Fail Step
        run: exit 1
