name: Load BDA_SECRET and Print Hash
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Load Secret and Print Hash
        run: |
          echo "Hash of Secret value is $(echo -n $BDA_SECRET | sha256sum)"
        env:
          BDA_SECRET: ${{ secrets.BDA_SECRET }}